### ISSUE TITLE
Clashing ids across tables

### ISSUE THREAD

**Issue by nitbharambe** [alliander-opensource/power-grid-model-io#39]
https://github.com/alliander-opensource/power-grid-model-io/blob/3e4b2ef96711128debda4cdef71a55e173efcf9f/src/power_grid_model_io/converters/tabular_converter.py#L305-L308

In vision, when there are two tables having same ids eg. `cables` and `reactance coils`, the keys would match exactly. For eg. if they have a common number say 1, the key generated would be 'line:Number=1'.

**Comment by bramstoeller** [comment]
This will be fixed in https://github.com/alliander-opensource/power-grid-model-io/issues/9. For now you can add a unique constant number in the id, like:

```yaml
cables:
  line:
    id:
      - Number
      - 0
    ...
reactance coil:
  line:
    id:
      - Number
      - 1
    ...
```
