### ISSUE TITLE
Make tabular mapping more explicit

### ISSUE THREAD

**Issue by petersalemink95** [alliander-opensource/power-grid-model-io#9]
It would be better to make the tabular mapping more explicit, e.g. use:

```
     p_specified:
        function:
          name: power_grid_model_io.utils.filters.multiply
          args:
            - P
            - reference:
                table: Nodes
                value_column: Simultaneity
                id_column: Number
                ref_column: Node.Number
```

or something similar, instead of:

```
      p_specified:
        power_grid_model_io.utils.filters.multiply:
          - P
          - Nodes!Simultaneity[Number=Node.Number]

```

**Comment by bramstoeller** [comment]
Suggestion (note that all is yaml notation and it's up to the user which specific format to choose):
```yaml
# simple column mapping:
u_rated: Vnom

# constant values (except strings):
u_rated: 400.0

# multiplications:
u_rated:
  multiply: [vn_kv, 1000.0]

# automatically generated ids
id:
  auto_id:
    component: node
    key: index
# or
id:
  auto_id:
    component: transformer
    key:
      - Node.Number
      - Subnumber
# or
id:
  auto_id:
    component: transformer
    key:
      node_number: Node.Number
      node_sub_number: Subnumber

# reference to automatically generated ids
from_node:
  auto_id: 
    component: node
    key: nodeA

# filters
i0:
  filter: 
    function: phase_to_phase.relative_no_load_current
    args:
      i_0: Io
      p_0:Po
      s_nom: Snom
      u_nom: Unom2

# reference to other tables
r1:
  reference:
    other_table: Cables
    search_column: Shortname
    query_column: Type short
    value_column: R

```
